
-- set schema
-- SET SCHEMA_SEARCH_PATH PUBLIC;

-- show table
show tables;

-- show table with select
SELECT
    TABLE_NAME
FROM
    INFORMATION_SCHEMA.TABLES
WHERE
    TABLE_SCHEMA = 'PUBLIC';
    -- AND TABLE_TYPE = 'BASE TABLE'


-- show column ( desc )
-- SHOW columns from LEADERBOARD_PLAYER;

-- desc with select (Get primary key)
SELECT
    col.COLUMN_NAME,
    col.DATA_TYPE,
    col.CHARACTER_MAXIMUM_LENGTH,
    col.IS_NULLABLE,
    col.COLUMN_DEFAULT,
    CASE WHEN kc.COLUMN_NAME IS NOT NULL THEN 'PRI' ELSE '' END AS IS_PRIMARY_KEY
FROM
    INFORMATION_SCHEMA.COLUMNS col
LEFT JOIN (
    SELECT
        tc.CONSTRAINT_NAME,
        kc.COLUMN_NAME
    FROM
        INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    JOIN
        INFORMATION_SCHEMA.KEY_COLUMN_USAGE kc
            ON tc.CONSTRAINT_NAME = kc.CONSTRAINT_NAME
            AND tc.TABLE_NAME = kc.TABLE_NAME
    WHERE
        tc.TABLE_NAME = 'LEADERBOARD_PLAYER'
        AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
) kc
    ON col.COLUMN_NAME = kc.COLUMN_NAME
WHERE
    col.TABLE_SCHEMA = 'PUBLIC'
    AND col.TABLE_NAME = 'LEADERBOARD_PLAYER';

-- desc with select
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE, COLUMN_DEFAULT
    FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'PUBLIC' AND TABLE_NAME = 'LEADERBOARD_PLAYER';


-- get primary key
SELECT
    tc.CONSTRAINT_NAME,
    tc.CONSTRAINT_TYPE,
    kc.COLUMN_NAME
FROM
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE kc
        ON tc.CONSTRAINT_NAME = kc.CONSTRAINT_NAME
        AND tc.TABLE_NAME = kc.TABLE_NAME
WHERE
    tc.TABLE_NAME = 'LEADERBOARD_PLAYER'
    AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'












SELECT * FROM LEADERBOARD_PLAYER;


DELETE FROM LEADERBOARD_PLAYER;
