/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parser;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.telegram.telegrambots.longpolling.TelegramBotsLongPollingApplication;
import org.telegram.telegrambots.meta.exceptions.TelegramApiException;

import java.util.Optional;

// import org.telegram.telegrambots.meta.TelegramBotsApi;
// import org.telegram.telegrambots.meta.exceptions.TelegramApiException;
// import org.telegram.telegrambots.updatesreceivers.DefaultBotSession;

import parser.db.Database;
import parser.schedule.ParseSchedular;
import parser.telegram.TelegramBot;

public class Main {

    static Logger logger = LogManager.getLogger(Main.class);

    private static void closeTelegramConnect(TelegramBotsLongPollingApplication botsApplication) {
        // Ensure this process wait forever
        try {
            botsApplication.close();
            logger.debug("disconnect Telegram");
        } catch (Exception e) {
            logger.error("disconnect Telegram Error");
            logger.error(e.getMessage());
        }
    }

    private static void closeConnect(TelegramBotsLongPollingApplication botsApplication, Database db) {
        // Ensure this process wait forever
        closeTelegramConnect(botsApplication);
        db.disconnectEntityManagerFactory();
        logger.debug("disconnect Database");
        logger.debug("End Done");
    }


    public static void main(String[] args)
        throws NullPointerException, TelegramApiException, InterruptedException
    {
        logger.info("start");
        System.out.println("start");
        try (TelegramBotsLongPollingApplication botsApplication = new TelegramBotsLongPollingApplication()) {
            // Database 연결
            Database db = new Database("growcastle");
            if (!db.connectEntityManagerFactory()) {
                logger.error("Database Connection Fail");
                closeTelegramConnect(botsApplication);
                return;
            }

            // 파싱 알림용 Telegram Bot 연결
            TelegramBot telegramBot = new TelegramBot(db, Optional.of("telegram"));
            botsApplication.registerBot(telegramBot.getAPIBotToken(), telegramBot);

            // 스케쥴러 강제종료에 대한 이벤트 추가
            Runtime.getRuntime().addShutdownHook(new Thread(() -> closeConnect(botsApplication, db)));
            logger.debug("Ready Done!");

            // Scheduler 등록 및 시작
            ParseSchedular schedular = new ParseSchedular(telegramBot, db);
            schedular.start();
            logger.debug("parse schedular start");

            // 모든 작업이 끝나면 아래 내용 진행
            Thread.currentThread().join();
            logger.debug("end");
        } catch (NullPointerException e) {
            throw e;
        } catch (InterruptedException e) {
            logger.warn("Interrupted Exception");
            Thread.currentThread().interrupt();
        } catch ( Exception e) {
            logger.error("Main Method Error");
            logger.error(e.getMessage());
            e.printStackTrace();
        }
    }

}
